// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace E_Shop.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    partial class ShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Car", b =>
                {
                    b.Property<int>("CarID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOnSale")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnStock")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ThumbNail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Car");

                    b.HasData(
                        new
                        {
                            CarID = 1,
                            Brand = "Audi",
                            CategoryID = 2,
                            Description = "25 years of RS, 25 years of high-performance station wagons from Audi: With the new Audi RS 6 Audi Sport is ushering in a new chapter in the history of the high-performance Avant. Even more power combined with increased efficiency thanks to mild hybrid system turn the RS 6 Avant into the perfect companion for any purpose. The new Audi RS 6 Avant will go on sale in dealerships in Germany and other European countries by the end of 2019.Combined fuel consumption in l / 100 km: 117(20.1) – 115(20.5),Combined CO2 emissions in g / km: 268(431.3) – 263(423.3); Information on fuel consumption and CO2 emissions aswell as efficiency classes in ranges depending on the tires and alloy wheel rims used",
                            Image = "\\Images\\rs6.jpg",
                            IsOnSale = true,
                            IsOnStock = true,
                            Model = "Rs6",
                            Price = 59999m,
                            ThumbNail = "\\Images\\rs6.jpg"
                        },
                        new
                        {
                            CarID = 2,
                            Brand = "Audi",
                            CategoryID = 1,
                            Description = "To create the S8, Audi takes its flagship A8 luxury sedan and adds a significant amount of power and poise. A standard twin-turbocharged V-8 engine provides the punch, while a firmer suspension and upgraded brakes improve the big sedan's athleticism. Subtle visual enhancements inside and out include different wheels, bumpers, and special interior trim. But the S8 otherwise looks similar to its A8 sibling, meaning that this car is not meant for those who want their luxury sedan to be ostentatious. The S8's spacious, feature-packed cabin makes it a perfect rival to V-8–powered variants of the BMW 7-series and the Mercedes-Benz S-class, and its digital dashboard makes the Audi perfect for high-rolling technophiles.",
                            Image = "\\Images\\s8.jpg",
                            IsOnSale = true,
                            IsOnStock = true,
                            Model = "S8",
                            Price = 80000m,
                            ThumbNail = "\\Images\\s8.jpg"
                        },
                        new
                        {
                            CarID = 3,
                            Brand = "Mercedes",
                            CategoryID = 1,
                            Description = "The Mercedes-AMG GT (C190 / R190) is a sports car produced in coupé and roadster bodystyles by German automobile manufacturer Mercedes-AMG. The car was introduced on 9 September 2014 and was officially unveiled to the public in October 2014 at the Paris Motor Show.[4] After the SLS AMG, it is the second sports car developed entirely in-house by Mercedes-AMG. Formula One driver Lewis Hamilton assisted with the development. The Mercedes-AMG GT went on sale in two variants (GT and GT S) in March 2015, while a GT3 racing variant of the car was introduced in 2015. A high performance variant called the GT R was introduced in 2016. A GT4 racing variant, targeted at semi-professional drivers and based on the GT R variant, was introduced in 2017. All variants are assembled at the Mercedes-Benz plant in Sindelfingen, Germany.",
                            Image = "\\Images\\gt.jpg",
                            IsOnSale = true,
                            IsOnStock = true,
                            Model = "AMG GT",
                            Price = 180000m,
                            ThumbNail = "\\Images\\gt.jpg"
                        },
                        new
                        {
                            CarID = 4,
                            Brand = "BMW",
                            CategoryID = 1,
                            Description = "The BMW i8 is a plug-in hybrid sports car developed by BMW. The i8 is part of BMW's electric fleet Project i being marketed as a new sub-brand, BMW i. The 2015 model year BMW i8 has a 7.1 kWh lithium-ion battery pack that delivers an all-electric range of 37 km (23 mi) under the New European Driving Cycle. Under the United States Environmental Protection Agency cycle, the range in EV mode is 24 km (15 mi) with a small amount of gasoline consumption. Its design is heavily influenced by the BMW M1 Homage concept car, which in turn pays homage to BMW's last production mid-engined sports car prior to the i8: the BMW M1. BMW will cease the production of the BMW i8 in April 2020",
                            Image = "\\Images\\i8.jpg",
                            IsOnSale = true,
                            IsOnStock = true,
                            Model = "I8",
                            Price = 99999m,
                            ThumbNail = "\\Images\\i8.jpg"
                        });
                });

            modelBuilder.Entity("Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryDescription = "",
                            CategoryName = "Sedan"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryDescription = "",
                            CategoryName = "Avant"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryDescription = "",
                            CategoryName = "HatchBack"
                        });
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Models.Car", b =>
                {
                    b.HasOne("Models.Category", "Category")
                        .WithMany("Cars")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
